package Mogul.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Mogul.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.12 16:36:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HyppyTest {



  // Generated by ComTest BEGIN
  /** testToString58 */
  @Test
  public void testToString58() {    // Hyppy: 58
    Hyppy hyppy = new Hyppy(2, "testihyppy", 0.5); 
    assertEquals("From: Hyppy line: 60", "2|testihyppy|0.5", hyppy.toString()); 
  } // Generated by ComTest END
}