package Mogul.test;
// Generated by ComTest BEGIN
import Mogul.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.12 16:36:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HypytTest {



  // Generated by ComTest BEGIN
  /** testIterator52 */
  @Test
  public void testIterator52() {    // Hypyt: 52
    Hypyt testit = new Hypyt(); 
    Hyppy testi1 = new Hyppy(1); testit.lisaa(testi1); 
    Hyppy testi2 = new Hyppy(2); testit.lisaa(testi2); 
    Hyppy testi3 = new Hyppy(3); testit.lisaa(testi3); 
    Hyppy testi4 = new Hyppy(4); testit.lisaa(testi4); 
    Hyppy testi5 = new Hyppy(5); testit.lisaa(testi5); 
    Iterator<Hyppy> i2 = testit.iterator(); 
    assertEquals("From: Hypyt line: 64", testi1, i2.next()); 
    assertEquals("From: Hypyt line: 65", testi2, i2.next()); 
    assertEquals("From: Hypyt line: 66", testi3, i2.next()); 
    assertEquals("From: Hypyt line: 67", testi4, i2.next()); 
    assertEquals("From: Hypyt line: 68", testi5, i2.next()); 
    int n = 0; 
    for (Hyppy hyp : testit){
    hyp.getId(); 
    n++; 
    }
    assertEquals("From: Hypyt line: 77", 5, n); 
  } // Generated by ComTest END
}