package Mogul.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Mogul.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.12 16:35:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KilpailuTest {



  // Generated by ComTest BEGIN
  /** testAnna75 */
  @Test
  public void testAnna75() {    // Kilpailu: 75
    Kilpailu kilpailu = new Kilpailu(); 
    Racer testi1 = new Racer(); Racer testi2 = new Racer(); 
    testi1.rekisteroi(); testi2.rekisteroi(); 
    kilpailu.lisaa(testi1); kilpailu.lisaa(testi2); 
    assertEquals("From: Kilpailu line: 80", 2, kilpailu.anna(0).getTunnusNro()); 
    assertEquals("From: Kilpailu line: 81", 3, kilpailu.anna(1).getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm93 */
  @Test
  public void testGetLkm93() {    // Kilpailu: 93
    Kilpailu kilpailu = new Kilpailu(); 
    Racer testi1 = new Racer(); Racer testi2 = new Racer(); Racer testi3 = new Racer(); 
    kilpailu.lisaa(testi1); kilpailu.lisaa(testi2); kilpailu.lisaa(testi3); 
    assertEquals("From: Kilpailu line: 97", 3, kilpailu.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi144 */
  @Test
  public void testGetNimi144() {    // Kilpailu: 144
    Kilpailu uusi = new Kilpailu(); 
    uusi.setKilpailunimi("Megaluokan testikisa"); 
    assertEquals("From: Kilpailu line: 147", "Megaluokan testikisa", uusi.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetRinne159 */
  @Test
  public void testGetRinne159() {    // Kilpailu: 159
    Kilpailu uusi = new Kilpailu(); 
    uusi.setPituus(250); 
    assertEquals("From: Kilpailu line: 162", 250, uusi.getRinne()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa176 */
  @Test
  public void testLisaa176() {    // Kilpailu: 176
    Racer testi = new Racer(); 
    testi.lisaa("Testietu", "Testisuku", 1, 12); 
    assertEquals("From: Kilpailu line: 179", "Testietu", testi.getEtunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKilpailija194 */
  @Test
  public void testGetKilpailija194() {    // Kilpailu: 194
    Kilpailu testikisa = new Kilpailu(); 
    testikisa.lisaa("Testi", "Testinen", 99,98); 
    assertEquals("From: Kilpailu line: 197", "Testinen", testikisa.getKilpailija(1).getSukunimi()); 
  } // Generated by ComTest END
}