package Mogul.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Mogul.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.12 16:34:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RacerTest {



  // Generated by ComTest BEGIN
  /** testSetHyppyid150 */
  @Test
  public void testSetHyppyid150() {    // Racer: 150
    Racer testi = new Racer(); 
    testi.setHyppyid(1); 
    assertEquals("From: Racer line: 153", 1, testi.getHyppyId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi326 */
  @Test
  public void testRekisteroi326() {    // Racer: 326
    Racer testi = new Racer(); 
    testi.rekisteroi(); 
    Racer testi2 = new Racer(); 
    testi2.rekisteroi(); 
    int n1 = testi.getTunnusNro(); 
    int n2 = testi2.getTunnusNro(); 
    assertEquals("From: Racer line: 333", n2-1, n1);
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetEtunimi429 */
  @Test
  public void testGetEtunimi429() {    // Racer: 429
    Racer testi = new Racer(); 
    testi.setEtunimi("Testiukko"); 
    assertEquals("From: Racer line: 432", "Testiukko", testi.getEtunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetHyppypisteet442 */
  @Test
  public void testGetHyppypisteet442() {    // Racer: 442
    Racer testi = new Racer(); 
    testi.setHyppypisteet(10.0); 
    assertEquals("From: Racer line: 445", 10.0, testi.getHyppypisteet(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKokonaispisteet471 */
  @Test
  public void testGetKokonaispisteet471() {    // Racer: 471
    Racer testi = new Racer(); 
    testi.setTekniikkapisteet(10.0); 
    testi.setAikapisteet(15.0); 
    testi.setHyppypisteet(23.0); 
    assertEquals("From: Racer line: 476", 48.0, testi.getKokonaispisteet(), 0.000001); 
  } // Generated by ComTest END
}